# Generated by Django 2.2.5 on 2019-10-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_uuid', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
    ]
